---
- name: "Add NGINX Signing Key"
  apt_key:
    url: http://nginx.org/packages/keys/nginx_signing.key
    state: present
  tags:
    - setup

- name: "Add NGINX Mainline Repository"
  apt_repository:
    repo: "{{item}}"
    state: present
  register: nginx_add_repository
  with_items:
    - deb http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
  when: ( nginx_repository == "mainline" )
  tags:
    - setup

- name: "Remove NGINX Mainline Repository"
  apt_repository:
    repo: "{{item}}"
    state: absent
  register: nginx_remove_repository
  with_items:
    - deb http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src http://nginx.org/packages/mainline/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
  when: ( nginx_repository != "mainline" )
  tags:
    - setup

- name: "Add NGINX Stable Repository"
  apt_repository:
    repo: "{{item}}"
    state: present
  register: nginx_add_repository
  with_items:
    - deb http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
  when: ( nginx_repository != "mainline" )
  tags:
    - setup

- name: "Remove NGINX Stable Repository"
  apt_repository:
    repo: "{{item}}"
    state: absent
  register: nginx_add_repository
  with_items:
    - deb http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
    - deb-src http://nginx.org/packages/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} nginx
  when: ( nginx_repository == "mainline" )
  tags:
    - setup

- name: "Update apt cache"
  apt:
    update_cache: true
  when: ( nginx_add_repository or nginx_remove_repository )

- name: "Install NGINX package"
  apt:
    name: "{{ nginx_package }}"
    state: present
    force: yes
  notify: "start NGINX"
  tags:
    - setup

- name: "Create nginx.conf"
  template:
    src: "{{ nginx_conf }}"
    dest: "{{ nginx_path }}/nginx.conf"
  notify: "reload NGINX"
  tags:
    - config

- name: "Disable NGINX default server"
  file:
    path: "{{ nginx_path }}/conf.d/default.conf"
    state: absent
  notify: "reload NGINX"
  tags:
    - config

- name: "Create Nginx sites config"
  template:
    src: "{{ nginx_site_conf }}"
    dest: "{{ nginx_path }}/conf.d/{{ nginx_site_conf | basename | regex_replace('.j2$', '') }}"
  notify: "reload NGINX"
  tags:
    - config
