---
- name: Ensure www directory exists
  file:
    state: directory
    path: /srv/www/
    owner: root
    group: root
    mode: 0755
  become: yes

- name: Ensure WordPress directory exists in /srv/www
  file:
    state: directory
    path: "/srv/www/{{ server_domain_name }}"
    mode: 0755
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
  become: yes

- name: Ensure content directory exists in /srv/www/
  file:
    state: directory
    path: "/srv/www/{{ server_domain_name }}/content"
    mode: 0755
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
  become: yes

- name: Ensure themes directory exists in /srv/www/[server_domain]/content
  file:
    state: directory
    path: "/srv/www/{{ server_domain_name }}/content/themes"
    mode: 0755
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
  become: yes

- name: Ensure plugins directory exists in /srv/www/[server_domain]/content
  file:
    state: directory
    path: "/srv/www/{{ server_domain_name }}/content/plugins"
    mode: 0755
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
  become: yes

- name: Ensure plugins-mu directory exists in /srv/www/[server_domain]/content
  file:
    state: directory
    path: "/srv/www/{{ server_domain_name }}/content/plugins-mu"
    mode: 0755
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
  become: yes

- name: Check if WordPress is downloaded
  stat:
    path: "/srv/www/{{ server_domain_name }}/index.php"
  register: check_wp_file

- name: Download WordPress
  get_url:
    url: https://wordpress.org/wordpress-{{ wp_version }}.tar.gz
    dest: /tmp/wordpress-{{ wp_version }}.tar.gz
    checksum: "sha1:{{ wp_sha1sum }}"
  become: yes
  when: not check_wp_file.stat.exists

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress-{{ wp_version }}.tar.gz
    dest: "/srv/www/{{ server_domain_name}}/"
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
    copy: no
  become: yes
  when: not check_wp_file.stat.exists

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Ensure wp-config.php is in place
  template:
    src: wp-config.php.j2
    dest: "/srv/www/{{ server_domain_name }}/wp-config.php"
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
    mode: 0600
  become: yes

- name: Register default theme directory
  template:
    src: register-theme-directory.php.j2
    dest: "/srv/www/{{ server_domain_name }}/content/plugins-mu/register-theme-directory.php"
    owner: "{{ server_unprivileged_user }}"
    group: "{{ server_unprivileged_group }}"
    mode: 0755
  become: yes

- name: Ensure NGINX site config is in place
  template:
    src: site.conf.j2
    dest: "/etc/nginx/conf.d/{{ server_domain_name }}.conf"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: "restart NGINX"
