---
# handlers file for ansible-role-php
- name: "start PHP-FPM"
  service:
    name: "{{ php_fpm_daemon }}"
    state: started
    enabled: yes
  when: php_enable_php_fpm

- name: "restart PHP-FPM"
  service:
    name: "{{ php_fpm_daemon }}"
    state: restarted
  when: php_enable_php_fpm
